# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Rens Holmer
  url:            
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/holmrenser
