# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            SynNetwork
tagline:          Combining synteny and phylogenetics in genefamilies
url:              http://holmrenser.github.io
paginate:         1
baseurl:          /
author:
  name:           Rens Holmer
  url:            
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/holmrenser
